// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnoGQbQF51tPMzxlXLBVnhtCqMgRt2NkM',
    appId: '1:886890617790:web:81b228c2189a2d535f77ef',
    messagingSenderId: '886890617790',
    projectId: 'john-e28e6',
    authDomain: 'john-e28e6.firebaseapp.com',
    storageBucket: 'john-e28e6.appspot.com',
    measurementId: 'G-Q9BCR1HNNW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlVVLDeJtTOfo-epCuE3JPTyesqesICzY',
    appId: '1:886890617790:android:8e028b8b62f9f7085f77ef',
    messagingSenderId: '886890617790',
    projectId: 'john-e28e6',
    storageBucket: 'john-e28e6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAIKLBf5HSyIUbHk8sSV-eOg0vT4zh2EY',
    appId: '1:886890617790:ios:5b4ec63bcf70628a5f77ef',
    messagingSenderId: '886890617790',
    projectId: 'john-e28e6',
    storageBucket: 'john-e28e6.appspot.com',
    iosBundleId: 'com.example.progJohn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAIKLBf5HSyIUbHk8sSV-eOg0vT4zh2EY',
    appId: '1:886890617790:ios:5b4ec63bcf70628a5f77ef',
    messagingSenderId: '886890617790',
    projectId: 'john-e28e6',
    storageBucket: 'john-e28e6.appspot.com',
    iosBundleId: 'com.example.progJohn',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCnoGQbQF51tPMzxlXLBVnhtCqMgRt2NkM',
    appId: '1:886890617790:web:a180630c3b2bead25f77ef',
    messagingSenderId: '886890617790',
    projectId: 'john-e28e6',
    authDomain: 'john-e28e6.firebaseapp.com',
    storageBucket: 'john-e28e6.appspot.com',
    measurementId: 'G-9J24YWXBBC',
  );
}
